shell:
  program: /usr/local/bin/fish

# Colors
colors:
  # Default colors
  primary:
    background: "#011526"
    foreground: "#acb4c2"
    bright_foreground: "#eeeeee"

  # Cursor colors
  cursor:
    text: "#080808"
    cursor: "#9ca1aa"

  # Selection colors
  selection:
    text: "#080808"
    background: "#b2ceee"

  # Normal colors
  normal:
    black: "#1d3b53"
    red: "#fc514e"
    green: "#a1cd5e"
    yellow: "#e3d18a"
    blue: "#82aaff"
    magenta: "#c792ea"
    cyan: "#7fdbca"
    white: "#a1aab8"

  # Bright colors
  bright:
    black: "#7c8f8f"
    red: "#ff5874"
    green: "#21c7a8"
    yellow: "#ecc48d"
    blue: "#82aaff"
    magenta: "#ae81ff"
    cyan: "#7fdbca"
    white: "#d6deeb"

background_opacity: 1.0

font:
  normal:
    family: "CaskaydiaCove Nerd Font"
    style: Regular
  bold:
    family: "CaskaydiaCove Nerd Font"
    style: Bold
  italic:
    family: "CaskaydiaCove Nerd Font"
    style: Italic
  bold_italic:
    family: "CaskaydiaCove Nerd Font"
    style: Bold Italic

  offset:
    x: 0
    y: 4

  size: 12.0

  glyph_offset:
    x: 0
    y: 3

  use_thin_strokes: false

  draw_bold_text_with_bright_colors: true

window:
  decorations: "buttonless"
  dimensions:
    columns: 187
    lines: 41
  position:
    x: 49
    y: 70
  padding:
    x: 10
    y: 8

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines te viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 10

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: false

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ? Block
    #   - _ Underline
    #   - | Beam
    shape: Beam

    # Cursor blinking state
    #
    # Values for `blinking`:
    #- Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Never
  vi_mode_style: None

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: Slash, mods: Control, chars: "\x1f" }
  - { key: Q, mods: Control, chars: "\x11" }
  #- { key: NumpadEnter, mods: Control, chars: "" }
