shell:
  program: /usr/local/bin/fish

colors:
  name: Neon
  author: ""
  primary:
    background: "#171717"
    foreground: "#f8f8f8"
  cursor:
    text: "#171717"
    cursor: "#f8f8f8"
  normal:
    black: "#171717"
    red: "#d81765"
    green: "#97d01a"
    yellow: "#ffa800"
    blue: "#82A0C1"
    magenta: "#ff2491"
    cyan: "#88C0D0"
    white: "#ebebeb"
  bright:
    #black: "#38252c" # original neon theme  
    black: "#4B5669"
    red: "#ff0000"
    green: "#76b639"
    yellow: "#e1a126"
    blue: "#289cd5"
    magenta: "#ff2491"
    cyan: "#0a9b81"
    white: "#f8f8f8"

background_opacity: 0.75

font:
  normal:
    family: "Hack Nerd Font"
    #family: "SauceCodePro Nerd Font"
    style: Regular
  bold:
    family: "Hack Nerd Font"
    #family: "SauceCodePro Nerd Font"
    style: Bold
  italic:
    family: "Hack Nerd Font"
    #family: "SauceCodePro Nerd Font"
    style: Italic
  bold_italic:
    family: "Hack Nerd Font"
    #family: "SauceCodePro Nerd Font"
    style: Bold Italic

  offset:
    x: 0
    y: 3

  size: 11.5

  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true

  draw_bold_text_with_bright_colors: true

window:
  dimensions:
    columns: 187
    lines: 44
  decorations: 'none'
  position:
    x: 49
    y: 70
  padding:
    x: 8
    y: 8

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines te viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 10

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ? Block
    #   - _ Underline
    #   - | Beam
    shape: Beam

    # Cursor blinking state
    #
    # Values for `blinking`:
       #- Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Never
  vi_mode_style: None

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - {
      key: NumpadSubtract,
      mods: Control,
      action: DecreaseFontSize
    }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: Slash, mods: Control, chars: "\x1f" }
  - { key: Q, mods: Control, chars: "\x11" }
  #- { key: NumpadEnter, mods: Control, chars: "" }
