shell:
  program: /usr/local/bin/fish

# Nightfox Alacritty Colors
# Style: nightfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox_alacritty.yml
colors:
  # Default colors
  primary:
    background: "0x192330"
    foreground: "0xcdcecf"
  # Normal colors
  normal:
    black: "0x393b44"
    red: "0xc94f6d"
    green: "0x81b29a"
    yellow: "0xdbc074"
    blue: "0x719cd6"
    magenta: "0x9d79d6"
    cyan: "0x63cdcf"
    white: "0xdfdfe0"
  # Bright colors
  bright:
    black: "0x475072"
    red: "0xd6616b"
    green: "0x58cd8b"
    yellow: "0xffe37e"
    blue: "0x84cee4"
    magenta: "0xb8a1e3"
    cyan: "0x59f0ff"
    white: "0xf2f2f2"
  indexed_colors:
    - { index: 16, color: "0xf4a261" }
    - { index: 17, color: "0xd67ad2" }

background_opacity: 1.0

font:
  normal:
    family: "SauceCodePro Nerd Font"
    style: Regular
  bold:
    family: "SauceCodePro Nerd Font"
    style: Bold
  italic:
    family: "SauceCodePro Nerd Font"
    style: Italic
  bold_italic:
    family: "SauceCodePro Nerd Font"
    style: Bold Italic

  offset:
    x: 0
    y: 3

  size: 12.0

  glyph_offset:
    x: 0
    y: 2

  use_thin_strokes: false

  draw_bold_text_with_bright_colors: true

window:
  decorations: "buttonless"
  dimensions:
    columns: 187
    lines: 41
  position:
    x: 49
    y: 70
  padding:
    x: 4
    y: 4

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines te viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 10

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: false

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ? Block
    #   - _ Underline
    #   - | Beam
    shape: Beam

    # Cursor blinking state
    #
    # Values for `blinking`:
    #- Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Never
  vi_mode_style: None

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: Slash, mods: Control, chars: "\x1f" }
  - { key: Q, mods: Control, chars: "\x11" }
  #- { key: NumpadEnter, mods: Control, chars: "" }
