if not vim.g.vscode then
  require 'general'
  require 'plug'
  require 'theme'
  require '_treesitter'
  require '_lsp'
  require '_colorizer'
  require '_lualine'
  require '_markdown'
  require '_nerdcommenter'
  require '_neoscroll'
  require '_nvimtree'
  require '_barbar'
  require '_telescope'
  require '_tmuxnavigator'
  require '_fugutivegit'
  require '_gitgutter'
  require '_anyfold'
  require '_tpipeline'
  require '_web_devicons'
  require '_scrollview'
  require '_easymotion'
  require 'mappings'
else
  print 'NVIM HAS STARTED 🚀'
end
