add_newline = true

format = """
$directory\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$character\
"""

[directory]
fish_style_pwd_dir_length = 3

[fill]
symbol = " "

[character]    
success_symbol = "[➜](bold green)" 

[package]
disabled = true

